import { useCallback, useEffect, useRef, useState } from "react";
import { web3Accounts, web3Enable, web3FromAddress } from "@polkadot/extension-dapp";
import { MiniCellsLocalRuntime, type LocalModel } from "./localInference";

const KEEPER = (import.meta.env.VITE_MINICELLS_KEEPER_URL || "http://127.0.0.1:8090").replace(/\/$/, "");
type Status = { chain: { generation?: number; model_hash?: string; pending_plus: boolean; pending_minus: boolean }; phase: string; last_error?: string };
type History = { generation: number; model_hash: string; plus_loss: number; minus_loss: number; tokens: number };
type Account = { address: string; name?: string };

export function App() {
  const [status, setStatus] = useState<Status>(); const [history, setHistory] = useState<History[]>([]); const [account, setAccount] = useState<Account>(); const [auth, setAuth] = useState(false); const [operator, setOperator] = useState(false); const [model, setModel] = useState<LocalModel>(); const [stale, setStale] = useState(false); const [text, setText] = useState("hello"); const [result, setResult] = useState<{ output: string; generation: number; modelHash: string }>(); const [error, setError] = useState(""); const runtime = useRef(new MiniCellsLocalRuntime());
  const refresh = useCallback(async () => { const [s, h] = await Promise.all([fetch(`${KEEPER}/v1/status`), fetch(`${KEEPER}/v1/history`)]); if (!s.ok) throw new Error(`Keeper status ${s.status}`); setStatus(await s.json()); if (h.ok) setHistory((await h.json()).items || []); }, []);
  const loadModel = useCallback(async () => { const response = await fetch(`${KEEPER}/v1/model`, { credentials: "include" }); if (!response.ok) throw new Error(`Model request ${response.status}`); const value = await response.json(); const bytes = Uint8Array.from(atob(value.modelBytes), char => char.charCodeAt(0)); await runtime.current.init(); runtime.current.setModel({ generation: value.generation, modelHash: value.modelHash, modelBytes: bytes }); setModel({ generation: value.generation, modelHash: value.modelHash, modelBytes: bytes }); setStale(false); }, []);
  const me = useCallback(async () => { const response = await fetch(`${KEEPER}/v1/auth/me`, { credentials: "include" }); const value = await response.json(); setAuth(Boolean(value.authenticated)); setOperator(Boolean(value.isOperator)); if (value.authenticated) await loadModel(); }, [loadModel]);
  useEffect(() => { void refresh().catch(e => setError(String(e))); void me().catch(e => setError(String(e))); const source = new EventSource(`${KEEPER}/v1/events`, { withCredentials: true }); const parse = (event: MessageEvent) => { try { return JSON.parse(event.data); } catch { return undefined; } }; source.addEventListener("snapshot", event => { const value = parse(event as MessageEvent); if (value?.data) setStatus(value.data); }); source.addEventListener("chain", event => { const value = parse(event as MessageEvent); if (value?.data) setStatus(old => old ? { ...old, chain: value.data } : old); }); source.addEventListener("training", event => { const value = parse(event as MessageEvent); const side = value?.data?.side; if (side) setStatus(old => old ? { ...old, chain: { ...old.chain, ...(side === "PLUS" ? { pending_plus: true } : { pending_minus: true }) } } : old); }); source.addEventListener("generation", event => { const value = parse(event as MessageEvent); if (value?.data?.generation !== undefined) { setStale(true); setStatus(old => old ? { ...old, chain: { ...old.chain, generation: value.data.generation } } : old); void loadModel().catch(e => setError(String(e))); } }); source.addEventListener("model", () => { setStale(true); void loadModel().catch(e => setError(String(e))); }); source.addEventListener("error", event => { const value = parse(event as MessageEvent); if (value?.data?.message) setError(value.data.message); }); source.onerror = () => setError("Keeper SSE disconnected; retrying…"); return () => source.close(); }, [loadModel, me, refresh]);
  async function connect() { try { setError(""); const extensions = await web3Enable("MINI Cells"); if (!extensions.length) throw new Error("No Polkadot wallet extension found"); const accounts = await web3Accounts(); const selected = accounts.find(value => value.type === "sr25519") || accounts[0]; if (!selected) throw new Error("No wallet account found"); const challengeResponse = await fetch(`${KEEPER}/v1/auth/challenge?account=${encodeURIComponent(selected.address)}`, { credentials: "include" }); const challenge = await challengeResponse.json(); if (!challengeResponse.ok) throw new Error(challenge.error); const injector = await web3FromAddress(selected.address); if (!injector.signer.signRaw) throw new Error("Wallet does not support signRaw"); const signed = await injector.signer.signRaw({ address: selected.address, data: challenge.messageHex, type: "bytes" }); const verified = await fetch(`${KEEPER}/v1/auth/verify`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ challengeId: challenge.challengeId, account: selected.address, signature: signed.signature }) }); const value = await verified.json(); if (!verified.ok) throw new Error(value.error); setAccount({ address: selected.address, name: selected.meta?.name }); setAuth(true); setOperator(Boolean(value.isOperator)); await loadModel(); } catch (e) { setError(String(e)); } }
  async function logout() { await fetch(`${KEEPER}/v1/auth/logout`, { method: "POST", credentials: "include" }); setAuth(false); setOperator(false); setAccount(undefined); setModel(undefined); setResult(undefined); }
  function infer() { try { if (!model) throw new Error("Connect a wallet and load a verified model first"); setResult(runtime.current.infer(text)); setError(""); } catch (e) { setError(String(e)); } }
  return <main><header><div><p className="eyebrow">Keeper · Wallet Auth · Local WASM</p><h1>MINI Cells</h1></div><div className="header-actions">{auth ? <><span className="badge active">{account?.name || account?.address.slice(0, 10)}{operator ? " · operator" : ""}</span><button onClick={() => void logout()}>Logout</button></> : <button onClick={() => void connect()}>Connect wallet</button>}</div></header>{error && <p className="error">{error}</p>}<section className="hero"><div><h2>Finalized status</h2><dl><Row label="Capability" value="ECHO"/><Row label="Chain generation" value={status?.chain.generation?.toString() ?? "Not initialized"}/><Row label="Pending" value={`${status?.chain.pending_plus ? "PLUS " : ""}${status?.chain.pending_minus ? "MINUS" : "clear"}`}/><Row label="Canonical model" value={status?.chain.model_hash ?? "—"}/></dl></div><div><h2>Local inference</h2><p>Inference runs in Rust/WASM in this browser. It does not submit MiniJAM Work.</p><Row label="Loaded generation" value={model?.generation?.toString() ?? "—"}/><Row label="Loaded model hash" value={model?.modelHash ?? "—"}/>{stale && <p className="error">Local model is stale; waiting for a verified refresh.</p>}<input maxLength={32} value={text} onChange={e => setText(e.target.value.toLowerCase())}/><button disabled={!auth || !model || stale} onClick={infer}>Run local inference</button>{result && <div className="result"><small>Generation {result.generation} · local WASM</small><strong>{result.output || "<PAD>"}</strong></div>}</div></section><section><div className="section-title"><div><p className="eyebrow">Official Keeper scheduler</p><h2>Training generations</h2><p>Training controls are not exposed to regular users.</p></div></div><div className="history"><div className="history-row head"><span>Generation</span><span>PLUS loss</span><span>MINUS loss</span><span>Tokens</span><span>Model</span></div>{history.map(h => <div className="history-row" key={h.generation}><span>{h.generation}</span><span>{h.plus_loss}</span><span>{h.minus_loss}</span><span>{h.tokens}</span><span>{h.model_hash.slice(0, 12)}…</span></div>)}</div></section></main>
}
function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
