import{useCallback,useEffect,useMemo,useState}from"react";import{api,waitOperation}from"./api/playground";import{signAction}from"./actions";import{ExtensionWallet,type WalletAccount}from"./wallet";import{base64,decodeHistory,decodeInference,decodeMeta,decodePending,hexBytes,historyKey,inferKey,inferenceSlot,inferWork,keyHex,keys,trainWork,type Meta}from"./codec";
const SERVICE=Number(import.meta.env.VITE_MINICELLS_SERVICE_ID);const wallet=new ExtensionWallet();const requestId=()=>BigInt(Date.now())*1000n+BigInt(Math.floor(Math.random()*1000));
async function storage(key:string){const result=await api.storage(SERVICE,keyHex(key));return result.value?hexBytes(result.value):undefined}
export function App(){const[meta,setMeta]=useState<Meta>();const[pending,setPending]=useState<Record<string,ReturnType<typeof decodePending>|undefined>>({});const[history,setHistory]=useState<ReturnType<typeof decodeHistory>[]>([]);const[account,setAccount]=useState<WalletAccount>();const[text,setText]=useState("hello");const[result,setResult]=useState<ReturnType<typeof decodeInference>>();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const refresh=useCallback(async()=>{if(!Number.isFinite(SERVICE))throw new Error("VITE_MINICELLS_SERVICE_ID is required");const raw=await storage(keys.meta);if(!raw){setMeta(undefined);return}const next=decodeMeta(raw);setMeta(next);const[p,m]=await Promise.all([storage(keys.plus),storage(keys.minus)]);setPending({PLUS:p?decodePending(p):undefined,MINUS:m?decodePending(m):undefined});const rows=[];for(let i=0;i<64;i++){const h=await storage(historyKey(i));if(h)rows.push(decodeHistory(h))}rows.sort((a,b)=>Number(b.generation-a.generation));setHistory(rows)},[]);
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));const timer=setInterval(()=>void refresh().catch(()=>{}),6000);return()=>clearInterval(timer)},[refresh]);
 async function connect(){try{const accounts=await wallet.connect();const selected=accounts.find(a=>a.type==="sr25519");if(!selected)throw new Error("No sr25519 account found");setAccount(selected)}catch(e){setError(String(e))}}
 async function submit(payload:Uint8Array){if(!account)throw new Error("Connect an sr25519 wallet first");const service=await api.service(SERVICE);const[metaSidecar,modelSidecar]=await Promise.all([storage(keys.meta),storage(keys.model)]);if(Boolean(metaSidecar)!==Boolean(modelSidecar))throw new Error("Finalized MINI Cells state is incomplete");const extrinsicsBase64=metaSidecar&&modelSidecar?[base64(metaSidecar),base64(modelSidecar)]:[];const params={serviceId:SERVICE,serviceCodeHash:service.codeHash,payloadBase64:base64(payload),extrinsicsBase64};const authorization=await signAction(wallet,account,params);return waitOperation(await api.work({authorization,...params}))}
 async function echo(){setBusy(true);setError("");try{const normalized=text.toLowerCase();setText(normalized);const id=requestId();await submit(inferWork(id,0xffffffffffffffffn,normalized));for(let i=0;i<60;i++){const raw=await storage(inferKey(inferenceSlot(id)));if(raw){const found=decodeInference(raw);if(found.requestId===id){setResult(found);return}}await new Promise(r=>setTimeout(r,1000))}throw new Error("Finalized inference record was not observed")}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function advance(){if(!meta)return;setBusy(true);setError("");try{if(!pending.PLUS)await submit(trainWork(2,requestId(),meta.generation,meta.modelHash));await refresh();const currentRaw=await storage(keys.meta);const current=currentRaw?decodeMeta(currentRaw):meta;const minus=await storage(keys.minus);if(!minus)await submit(trainWork(3,requestId(),current.generation,current.modelHash));await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <main><header><div><p className="eyebrow">Stage 01 · Echo</p><h1>MINI Cells</h1></div><button onClick={()=>void connect()}>{account?`${account.name} connected`:"Connect sr25519 wallet"}</button></header>{error&&<p className="error">{error}</p>}<section className="hero"><div><h2>Canonical status</h2><dl><Row label="Capability" value="ECHO"/><Row label="Generation" value={meta?.generation.toString()??"Not initialized"}/><Row label="Parameters" value="4,476"/><Row label="Model hash" value={meta?.modelHash??"—"}/><Row label="Latest candidate" value={meta?`${meta.loss} · ${meta.correct}/${meta.tokens}`:"—"}/></dl><div className="pending"><Badge name="PLUS" value={pending.PLUS}/><Badge name="MINUS" value={pending.MINUS}/></div></div><div><h2>Echo</h2><p>Lowercase text, at most 32 supported characters. The displayed answer is read from finalized Service storage.</p><input maxLength={32} value={text} onChange={e=>setText(e.target.value.toLowerCase())}/><button disabled={busy||!account} onClick={()=>void echo()}>Submit signed INFER</button>{result&&<div className="result"><small>Generation {result.generation.toString()}</small><strong>{result.output||"<PAD>"}</strong><span>{result.matching}/{result.input.length} matching tokens</span></div>}</div></section><section><div className="section-title"><div><p className="eyebrow">Canonical Sign-SPSA</p><h2>Training generations</h2><p>These are training generations; native AI learning quality is not yet validated.</p></div><button disabled={busy||!account||!meta} onClick={()=>void advance()}>Advance one generation</button></div><div className="history"><div className="history-row head"><span>Generation</span><span>PLUS loss</span><span>MINUS loss</span><span>Correct</span><span>Updated</span></div>{history.map(h=><div className="history-row" key={h.generation.toString()}><span>{h.generation.toString()}</span><span>{h.plusLoss.toString()}</span><span>{h.minusLoss.toString()}</span><span>{Math.max(h.plusCorrect,h.minusCorrect)}/{h.tokens}</span><span>{h.updated?"yes":"tie"}</span></div>)}</div></section></main>}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}function Badge({name,value}:{name:string;value:ReturnType<typeof decodePending>|undefined}){return <div className={value?"badge active":"badge"}><b>{name}</b><span>{value?`pending · loss ${value.loss}`:"clear"}</span></div>}
