import { useEffect, useState } from "react";

const KEEPER = (import.meta.env.VITE_MINICELLS_KEEPER_URL || "http://127.0.0.1:8090").replace(/\/$/, "");
type Status = { chain: { generation?: number; model_hash?: string; pending_plus: boolean; pending_minus: boolean }; phase: string; last_error?: string };
type History = { generation: number; model_hash: string; plus_loss: number; minus_loss: number; tokens: number };
type Inference = { request_id: number; status: string; error?: string };

export function App() {
  const [status, setStatus] = useState<Status>(); const [history, setHistory] = useState<History[]>([]); const [text, setText] = useState("hello"); const [inference, setInference] = useState<Inference>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function refresh() { const [s, h] = await Promise.all([fetch(`${KEEPER}/v1/status`), fetch(`${KEEPER}/v1/history`)]); if (!s.ok) throw new Error(`Keeper status ${s.status}`); setStatus(await s.json()); setHistory((await h.json()).items || []); }
  useEffect(() => { void refresh().catch(e => setError(String(e))); const source = new EventSource(`${KEEPER}/v1/events`); source.onmessage = event => { try { const value = JSON.parse(event.data); if (value.type === "snapshot") setStatus(value.data); } catch { /* reconnect is handled by EventSource */ } }; source.onerror = () => setError("Keeper SSE disconnected; retrying…"); return () => source.close(); }, []);
  async function infer() { setBusy(true); setError(""); try { const response = await fetch(`${KEEPER}/v1/infer`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text: text.toLowerCase() }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setInference(value); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  async function toggleTraining() { const enabled = !Boolean(status?.phase === "training"); await fetch(`${KEEPER}/v1/training`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled }) }); await refresh(); }
  return <main><header><div><p className="eyebrow">Keeper · State Plane</p><h1>MINI Cells</h1></div><span className="badge active">{status?.phase || "connecting"}</span></header>{error && <p className="error">{error}</p>}<section className="hero"><div><h2>Canonical status</h2><dl><Row label="Capability" value="ECHO"/><Row label="Generation" value={status?.chain.generation?.toString() ?? "Not initialized"}/><Row label="Model hash" value={status?.chain.model_hash ?? "—"}/><Row label="Pending" value={`${status?.chain.pending_plus ? "PLUS " : ""}${status?.chain.pending_minus ? "MINUS" : "clear"}`}/></dl></div><div><h2>Echo</h2><p>The Keeper submits direct MiniJAM Work and exposes finalized state through SSE. No browser wallet is required.</p><input maxLength={32} value={text} onChange={e => setText(e.target.value.toLowerCase())}/><button disabled={busy} onClick={() => void infer()}>Submit INFER</button>{inference && <div className="result"><small>Request {inference.request_id}</small><strong>{inference.status}</strong></div>}</div></section><section><div className="section-title"><div><p className="eyebrow">Keeper scheduler</p><h2>Training generations</h2><p>Training quality remains an explicit, unvalidated research metric.</p></div><button onClick={() => void toggleTraining()}>Toggle training</button></div><div className="history"><div className="history-row head"><span>Generation</span><span>PLUS loss</span><span>MINUS loss</span><span>Tokens</span><span>Model</span></div>{history.map(h => <div className="history-row" key={h.generation}><span>{h.generation}</span><span>{h.plus_loss}</span><span>{h.minus_loss}</span><span>{h.tokens}</span><span>{h.model_hash.slice(0, 12)}…</span></div>)}</div></section></main>
}
function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
