[package]
name = "minicells-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
minicells-chain = { path = "../minicells-chain" }
minicells-protocol = { path = "../minicells-protocol" }
clap.workspace = true
hex.workspace = true
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", rev = "2e4dd0bc22366a5af820492528869a493b5a5208", default-features = true }
tokio.workspace = true
