export const keys={meta:"mc:v1:meta",model:"mc:v1:model",plus:"mc:v1:pending:plus",minus:"mc:v1:pending:minus"};
export function hexBytes(text:string){if(!/^0x(?:[0-9a-f]{2})*$/i.test(text))throw new Error("invalid hex");return Uint8Array.from(text.slice(2).match(/../g)?.map(x=>parseInt(x,16))??[])}export function bytesHex(bytes:Uint8Array){return"0x"+[...bytes].map(x=>x.toString(16).padStart(2,"0")).join("")}export function keyHex(key:string){return bytesHex(new TextEncoder().encode(key))}export function base64(bytes:Uint8Array){let s="";bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
class Reader{view:DataView;offset=0;constructor(public b:Uint8Array){this.view=new DataView(b.buffer,b.byteOffset,b.byteLength)}u8(){return this.view.getUint8(this.offset++)}u16(){const v=this.view.getUint16(this.offset,true);this.offset+=2;return v}u32(){const v=this.view.getUint32(this.offset,true);this.offset+=4;return v}u64(){const v=this.view.getBigUint64(this.offset,true);this.offset+=8;return v}i64(){const v=this.view.getBigInt64(this.offset,true);this.offset+=8;return v}take(n:number){const v=this.b.slice(this.offset,this.offset+n);this.offset+=n;return v}}
export interface Meta{generation:bigint;modelHash:string;loss:bigint;correct:number;tokens:number;historyHead:number;stale:bigint;duplicates:bigint}
export function decodeMeta(bytes:Uint8Array):Meta{if(bytes.length!==128||new TextDecoder().decode(bytes.slice(0,4))!=="MCV1")throw new Error("invalid MetaV1");const r=new Reader(bytes);r.take(4);r.take(8);const generation=r.u64(),modelHash=bytesHex(r.take(32)),loss=r.i64(),correct=r.u32(),tokens=r.u32();r.take(24);const historyHead=r.u8();r.take(3);r.take(16);const stale=r.u64(),duplicates=r.u64();return{generation,modelHash,loss,correct,tokens,historyHead,stale,duplicates}}
export function decodePending(bytes:Uint8Array){const r=new Reader(bytes);const generation=r.u64();r.take(32);const side=r.u8()===1?"PLUS":"MINUS";const loss=r.i64();const correct=r.u32(),tokens=r.u32();return{generation,side,loss,correct,tokens}}
export function decodeHistory(bytes:Uint8Array){const r=new Reader(bytes);return{generation:r.u64(),parent:bytesHex(r.take(32)),modelHash:bytesHex(r.take(32)),plusLoss:r.i64(),minusLoss:r.i64(),plusCorrect:r.u32(),minusCorrect:r.u32(),tokens:r.u32(),updated:Boolean(r.u8())}}
export function decodeInference(bytes:Uint8Array){const r=new Reader(bytes);const requestId=r.u64(),generation=r.u64(),modelHash=bytesHex(r.take(32)),inputLen=r.u8(),outputLen=r.u8(),input=new TextDecoder().decode(r.take(32).slice(0,inputLen)),output=new TextDecoder().decode(r.take(32).slice(0,outputLen)),matching=r.u8();return{requestId,generation,modelHash,input,output,matching}}
function common(op:number,requestId:bigint){const b=new Uint8Array(64);b.set(new TextEncoder().encode("MCW1"));b[4]=1;b[5]=op;new DataView(b.buffer).setBigUint64(8,requestId,true);return b}
export function inferWork(requestId:bigint,generation:bigint,text:string){const data=new TextEncoder().encode(text);if(data.length>32)throw new Error("Maximum Echo length is 32");for(const c of text)if(!"abcdefghijklmnopqrstuvwxyz0123456789 .,?!'-".includes(c))throw new Error(`Unsupported character: ${c}`);const b=common(1,requestId);const v=new DataView(b.buffer);v.setBigUint64(16,generation,true);b[24]=data.length;b.set(data,25);return b.slice(0,25+data.length)}
export function trainWork(op:2|3,requestId:bigint,generation:bigint,hash:string){const b=common(op,requestId);new DataView(b.buffer).setBigUint64(16,generation,true);b.set(hexBytes(hash),24);return b.slice(0,56)}
export function inferenceSlot(id:bigint){let x=id;x^=x>>33n;x=BigInt.asUintN(64,x*0xff51afd7ed558ccdn);x^=x>>33n;return Number(x&15n)}export function historyKey(slot:number){return`mc:v1:history:${String(slot%64).padStart(2,"0")}`}export function inferKey(slot:number){return`mc:v1:infer:${String(slot%16).padStart(2,"0")}`}
