"""Training/evaluation primitives for CLM-0.4-mini M1.

Base-pretraining defaults are implementation constants, not calibration knobs.
The frozen protocol lock records the code commit/tree that defines them.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import math
from pathlib import Path
import random
import time
from typing import Iterable

import numpy as np
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset

from .curriculum import TextExample
from .examples import ScoredTokenExample, collate_scored
from .model import TinyCLMDecoder
from .protocol import CandidateOptimizerConfig
from .tokenizer import TokenizerBundle


@dataclass(frozen=True)
class BaseTrainConfig:
    optimizer: str = "AdamW"
    learning_rate: float = 3e-4
    weight_decay: float = 0.1
    beta1: float = 0.9
    beta2: float = 0.95
    batch_size: int = 64
    warmup_fraction: float = 0.02
    gradient_clip_norm: float = 1.0

    def to_dict(self) -> dict:
        return {
            "optimizer": self.optimizer,
            "learning_rate": self.learning_rate,
            "weight_decay": self.weight_decay,
            "betas": [self.beta1, self.beta2],
            "batch_size": self.batch_size,
            "warmup_fraction": self.warmup_fraction,
            "gradient_clip_norm": self.gradient_clip_norm,
        }


class BaseCorpusDataset(Dataset):
    """Read memory-mappable `.npy` shards generated by `BaseShardWriter`."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)
        self.manifest = json.loads(
            (self.root / "base-corpus-manifest.json").read_text(encoding="utf-8")
        )
        self.address_table = json.loads(
            (self.root / self.manifest["address_table"]["path"]).read_text(encoding="utf-8")
        )
        self.shards: list[dict] = []
        self.offsets: list[int] = [0]
        for item in self.manifest["shards"]:
            files = item["files"]
            shard = {
                "tokens": np.load(self.root / files["tokens"]["path"], mmap_mode="r"),
                "lengths": np.load(self.root / files["lengths"]["path"], mmap_mode="r"),
                "addresses": np.load(self.root / files["addresses"]["path"], mmap_mode="r"),
                "categories": np.load(self.root / files["categories"]["path"], mmap_mode="r"),
            }
            self.shards.append(shard)
            self.offsets.append(self.offsets[-1] + int(item["sequences"]))

    def __len__(self) -> int:
        return self.offsets[-1]

    def _locate(self, index: int) -> tuple[dict, int]:
        if index < 0:
            index += len(self)
        if index < 0 or index >= len(self):
            raise IndexError(index)
        import bisect

        shard_index = bisect.bisect_right(self.offsets, index) - 1
        local = index - self.offsets[shard_index]
        return self.shards[shard_index], local

    def __getitem__(self, index: int) -> tuple[np.ndarray, int, str, int]:
        shard, local = self._locate(int(index))
        length = int(shard["lengths"][local])
        tokens = np.asarray(shard["tokens"][local, :length], dtype=np.int64)
        address = str(self.address_table[int(shard["addresses"][local])])
        category = int(shard["categories"][local])
        return tokens, length, address, category


def collate_base(batch: list[tuple[np.ndarray, int, str, int]], *, pad_id: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, list[str]]:
    target_length = max(length - 1 for _, length, _, _ in batch)
    x = torch.full((len(batch), target_length), int(pad_id), dtype=torch.long)
    y = torch.full_like(x, int(pad_id))
    mask = torch.zeros((len(batch), target_length), dtype=torch.bool)
    addresses: list[str] = []
    for row, (tokens, length, address, _) in enumerate(batch):
        effective = int(length) - 1
        values = torch.from_numpy(np.asarray(tokens, dtype=np.int64))
        x[row, :effective] = values[:-1]
        y[row, :effective] = values[1:]
        mask[row, :effective] = True
        addresses.append(address)
    return x, y, mask, addresses


def _masked_ce(logits: torch.Tensor, targets: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    per_token = F.cross_entropy(
        logits.reshape(-1, logits.size(-1)), targets.reshape(-1), reduction="none"
    ).reshape_as(targets)
    selected = per_token[mask]
    if selected.numel() == 0:
        raise RuntimeError("evaluation/training batch has no scored tokens")
    return selected.mean()


def mean_scored_nll(
    model: TinyCLMDecoder,
    examples: Iterable[ScoredTokenExample],
    *,
    tokenizer: TokenizerBundle,
    device: torch.device,
    batch_size: int = 64,
) -> float:
    items = list(examples)
    if not items:
        return 0.0
    model.eval()
    total_loss = 0.0
    total_tokens = 0
    with torch.no_grad():
        for start in range(0, len(items), int(batch_size)):
            batch = items[start : start + int(batch_size)]
            x, y, mask, addresses = collate_scored(batch, pad_id=tokenizer.pad_id, device=device)
            logits = model(x, addresses)
            per_token = F.cross_entropy(
                logits.reshape(-1, logits.size(-1)), y.reshape(-1), reduction="none"
            ).reshape_as(y)
            total_loss += float(per_token[mask].sum().detach().cpu())
            total_tokens += int(mask.sum().item())
    return total_loss / float(max(1, total_tokens))


def train_only_cells(
    model: TinyCLMDecoder,
    *,
    cell_ids: list[str],
    examples: list[ScoredTokenExample],
    tokenizer: TokenizerBundle,
    optimizer_config: CandidateOptimizerConfig,
    device: torch.device,
    rng_seed: int,
) -> dict:
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    params: list[nn.Parameter] = []
    for module in model.modules_for_cell_ids(cell_ids):
        for parameter in module.parameters():
            parameter.requires_grad_(True)
            params.append(parameter)
    if not params:
        raise RuntimeError("candidate has no mutable Cell parameters")
    if optimizer_config.optimizer != "AdamW":
        raise ValueError("registered candidate optimizer must be AdamW")
    optimizer = torch.optim.AdamW(
        params,
        lr=optimizer_config.learning_rate,
        weight_decay=optimizer_config.weight_decay,
    )
    rng = random.Random(int(rng_seed))
    started = time.perf_counter()
    model.train()
    training_tokens = 0
    for _ in range(int(optimizer_config.steps)):
        if len(examples) <= optimizer_config.batch_size:
            batch = list(examples)
        else:
            indices = rng.sample(range(len(examples)), int(optimizer_config.batch_size))
            batch = [examples[index] for index in indices]
        x, y, mask, addresses = collate_scored(
            batch, pad_id=tokenizer.pad_id, device=device
        )
        optimizer.zero_grad(set_to_none=True)
        logits = model(x, addresses)
        loss = _masked_ce(logits, y, mask)
        loss.backward()
        optimizer.step()
        training_tokens += int(mask.sum().item())
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    return {
        "wall_seconds": time.perf_counter() - started,
        "training_tokens": int(training_tokens),
        "optimizer_steps": int(optimizer_config.steps),
    }


def train_base_model(
    model: TinyCLMDecoder,
    *,
    dataset: BaseCorpusDataset,
    tokenizer: TokenizerBundle,
    device: torch.device,
    seed: int,
    config: BaseTrainConfig | None = None,
) -> dict:
    """One deterministic pass over the registered 30M-token base corpus."""
    cfg = config or BaseTrainConfig()
    generator = torch.Generator().manual_seed(int(seed))
    loader = DataLoader(
        dataset,
        batch_size=cfg.batch_size,
        shuffle=True,
        generator=generator,
        num_workers=0,
        collate_fn=lambda batch: collate_base(batch, pad_id=tokenizer.pad_id),
    )
    for parameter in model.parameters():
        parameter.requires_grad_(True)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=cfg.learning_rate,
        weight_decay=cfg.weight_decay,
        betas=(cfg.beta1, cfg.beta2),
    )
    total_steps = max(1, len(loader))
    warmup_steps = max(1, int(round(total_steps * cfg.warmup_fraction)))

    def lr_scale(step: int) -> float:
        if step < warmup_steps:
            return float(step + 1) / float(warmup_steps)
        progress = (step - warmup_steps) / float(max(1, total_steps - warmup_steps))
        return 0.5 * (1.0 + math.cos(math.pi * min(1.0, progress)))

    started = time.perf_counter()
    loss_sum = 0.0
    token_count = 0
    model.train()
    for step, (x, y, mask, addresses) in enumerate(loader):
        x, y, mask = x.to(device), y.to(device), mask.to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(x, addresses)
        loss = _masked_ce(logits, y, mask)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.gradient_clip_norm)
        scale = lr_scale(step)
        for group in optimizer.param_groups:
            group["lr"] = cfg.learning_rate * scale
        optimizer.step()
        scored = int(mask.sum().item())
        loss_sum += float(loss.detach().cpu()) * scored
        token_count += scored
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    return {
        "optimizer": cfg.to_dict(),
        "steps": total_steps,
        "training_tokens": token_count,
        "mean_nll": loss_sum / float(max(1, token_count)),
        "wall_seconds": time.perf_counter() - started,
    }


def base_cell_activation_counts(model: TinyCLMDecoder, dataset: BaseCorpusDataset) -> dict[str, int]:
    counts = {
        model.sparse_layer(layer).base_cell_id(index): 0
        for layer in (3, 4)
        for index in range(model.cfg.base_cells)
    }
    for index in range(len(dataset)):
        _, _, address, _ = dataset[index]
        for cell_id in model.base_cell_ids(address):
            counts[cell_id] += 1
    return counts


def _normalize_answer(text: str) -> str:
    return " ".join(text.strip().lower().replace(".", "").split())


def greedy_answer(
    model: TinyCLMDecoder,
    *,
    prompt: str,
    address_id: str,
    tokenizer: TokenizerBundle,
    device: torch.device,
    max_new_tokens: int = 12,
) -> str:
    prompt_ids = tokenizer.encode(prompt, add_special_tokens=False)
    ids = [tokenizer.bos_id, *prompt_ids]
    model.eval()
    with torch.no_grad():
        for _ in range(int(max_new_tokens)):
            context = ids[-model.cfg.max_seq_len :]
            x = torch.tensor([context], dtype=torch.long, device=device)
            logits = model(x, [address_id])
            token = int(logits[0, -1].argmax().item())
            if token == tokenizer.eos_id:
                break
            ids.append(token)
    generated = ids[1 + len(prompt_ids) :]
    return tokenizer.decode(generated)


def exact_match_accuracy(
    model: TinyCLMDecoder,
    examples: Iterable[TextExample],
    *,
    tokenizer: TokenizerBundle,
    device: torch.device,
) -> float:
    items = list(examples)
    if not items:
        return 0.0
    correct = 0
    for example in items:
        predicted = greedy_answer(
            model,
            prompt=example.prompt,
            address_id=example.address_id,
            tokenizer=tokenizer,
            device=device,
        )
        if _normalize_answer(predicted) == _normalize_answer(example.answer):
            correct += 1
    return correct / float(len(items))
