#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'research'))
from minicells.fixed_v1 import pack_model,model_hash

EXPECTED={'num_cells':64,'max_seq_len':32,'vocab_size':44,'embedding_dim':8,'hidden_dim':16,'radius':2,'iterations':4,'mlp_width':32}
ORDER=('embedding.weight','update_in.weight','update_in.bias','update_out.weight','update_out.bias','output.weight','output.bias')
def main():
 import torch
 p=argparse.ArgumentParser();p.add_argument('checkpoint');p.add_argument('--output-dir',default='service/generated/imported');a=p.parse_args();payload=torch.load(a.checkpoint,map_location='cpu',weights_only=False);config=payload['config']['model']
 for key,value in EXPECTED.items():
  if config.get(key)!=value:raise SystemExit(f'architecture mismatch: {key}={config.get(key)!r}, expected {value}')
 state=payload['model_state_dict'];values=[]
 for name in ORDER:values.extend(round(float(x)*256) for x in state[name].reshape(-1))
 packed=pack_model(values);digest=model_hash(packed).hex();out=Path(a.output_dir);out.mkdir(parents=True,exist_ok=True);(out/'model.bin').write_bytes(packed)
 rust=['// Generated by tools/export_checkpoint.py; do not edit.',f'pub const IMPORTED_MODEL_HASH_HEX: &str = "0x{digest}";','pub const IMPORTED_MODEL: [i16; 4476] = [']
 rust += ['    '+', '.join(map(str,values[i:i+24]))+',' for i in range(0,len(values),24)];rust.append('];');(out/'model.rs').write_text('\n'.join(rust)+'\n');(out/'metadata.json').write_text(json.dumps({'format':'minicells.model.v1','source':a.checkpoint,'model_hash':'0x'+digest,'parameter_count':len(values)},indent=2)+'\n')
if __name__=='__main__':main()
