#!/usr/bin/env python3
"""Generate deterministic Model Format V1 genesis using documented SplitMix64."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path

COUNT=4476; MASK=(1<<64)-1
def splitmix(state):
    state=(state+0x9E3779B97F4A7C15)&MASK; z=state
    z=((z^(z>>30))*0xBF58476D1CE4E5B9)&MASK
    z=((z^(z>>27))*0x94D049BB133111EB)&MASK
    return state,z^(z>>31)
def main():
    p=argparse.ArgumentParser();p.add_argument('--seed',type=int,default=1);p.add_argument('--output',default='service/generated/genesis_model.rs');p.add_argument('--metadata',default='service/generated/genesis_model.json');p.add_argument('--packed',default='service/generated/genesis_model.bin');a=p.parse_args()
    state=a.seed&MASK; values=[]
    for _ in range(COUNT): state,value=splitmix(state);values.append(value%33-16)
    packed=b''.join(int(v).to_bytes(2,'little',signed=True) for v in values)
    digest=hashlib.blake2b(b'mini-cells:model:v1'+packed,digest_size=32).hexdigest()
    lines=['// Generated by tools/generate_random_genesis.py; do not edit.','pub const GENESIS_SEED: u64 = %d;'%a.seed,'pub const GENESIS_MODEL_HASH_HEX: &str = "0x%s";'%digest,'pub const GENESIS_MODEL: [i16; 4476] = [']
    lines += ['    '+', '.join(map(str,values[i:i+24]))+',' for i in range(0,COUNT,24)];lines.append('];')
    Path(a.output).parent.mkdir(parents=True,exist_ok=True);Path(a.output).write_text('\n'.join(lines)+'\n')
    Path(a.metadata).write_text(json.dumps({'format':'minicells.genesis.v1','prng':'splitmix64','seed':a.seed,'range_q':[-16,16],'parameter_count':COUNT,'model_hash':'0x'+digest},indent=2)+'\n')
    Path(a.packed).write_bytes(packed)
if __name__=='__main__':main()
