[package]
name = "minicells-chain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bounded-collections.workspace = true
cid.workspace = true
minijam-bulletin-api = { path = "../../.deps/minijam-client/crates/minijam-bulletin-api" }
minijam-chain-client = { path = "../../.deps/minijam-client/crates/minijam-chain-client" }
minijam-protocol-external = { package = "minijam-protocol", path = "../../.deps/minijam-client/crates/minijam-protocol" }
minijam-work-package-builder = { path = "../../.deps/minijam-client/crates/minijam-work-package-builder" }
minicells-protocol = { path = "../minicells-protocol" }
hex.workspace = true
multihash.workspace = true
parity-scale-codec = { version = "3.7.5", default-features = false, features = ["derive"] }
serde.workspace = true
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", rev = "2e4dd0bc22366a5af820492528869a493b5a5208", default-features = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
